
[build]
  base = "."
  publish = "public/"
  command = "yarn && gatsby build"

  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = true
    minify = true
  [build.processing.js]
    bundle = true
    minify = true
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true
  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

 [headers]
# Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"


#[[headers]]
#  for = "/*" # This defines which paths this specific [[headers]] block will cover.
#  [headers.values]
#    X-Frame-Options = "DENY"
#    X-XSS-Protection = "1; mode=block"
#    Content-Security-Policy = "frame-ancestors https://www.facebook.com"
#    # Multi-key header rules are expressed with multi-line strings
#    Link = '''
#    </assets/css/base.css>; rel=preload; as=style, \
#    </assets/css/base2.css>; rel=preload; as=style, \
#    </assets/css/base3.css>; rel=preload; as=style'''
#    # Basic-Auth allows you to password protect your whole site but is only available
#    # to paid accounts
#    Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"